name: Deploy Logic App to UAT

on:
  workflow_dispatch:   
  push:
    branches:
      - main

# Remove permissions section for client secret auth
# permissions:
#   id-token: write
#   contents: read

jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Logic App to UAT
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: "AnshulSinha-rg"
          template: ./template.json
          parameters: ./parameters-uat.json
          deploymentName: logicapp-uat-deployment
